version: 1

project_name: ui-plugin-operator

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "github.com/rancher/ui-plugin-operator/pkg/version.Version=v{{ .Version }}" -X "github.com/rancher/ui-plugin-operator/pkg/version.GitCommit={{ .ShortCommit }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

