# Default values for sample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: scresporancher/ui-plugin-operator
  pullPolicy: Always
  tag: "0.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

replicas: 1

resources: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: []

global:
  cattle:
    systemDefaultRegistry: ""
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2
    pullPolicy: IfNotPresent
  rbac:
    ## Create RBAC resources for ServiceAccounts and users
    ##
    enabled: false
    # create: true
    # userRoles:
    #   ## Create default user ClusterRoles to allow users to interact with Prometheus CRs, ConfigMaps, and Secrets
    #   create: true
    #   ## Aggregate default user ClusterRoles into default k8s ClusterRoles
    #   aggregateToDefaultRoles: true

    # pspEnabled: true
    # pspAnnotations: {}

debug: false
debugLevel: 0
