name: Release ui-plugin-operator
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print out contents of dist/
        run: |
          ls dist
          tree dist

      - name: Release ui-plugin-operator on github
        run: echo "not implemented"

      - name: Build and push container image to dockerhub
        run: echo "not implemented"
